### ISSUE TITLE
Error in cheta update

### ISSUE THREAD

**Issue by javierggt** [sot/eng_archive#180]
I don't know if this is "an issue" but it is certainly an issue I am having :-)
```
2019-11-08 16:34:31,493 Running cheta_update_client_archive version 4.47

...

2019-11-08 16:32:41,199 Processing 5min data for acis2eng
2019-11-08 16:32:41,290 Reading update date file https://icxc.cfa.harvard.edu/aspect/cheta/sync/acis2eng/2019-11-04T0033z/5min.pkl.gz
2019-11-08 16:32:41,296   elapsed time: 0.007 sec
2019-11-08 16:32:41,393 Reading update date file https://icxc.cfa.harvard.edu/aspect/cheta/sync/acis2eng/2019-11-05T0342z/5min.pkl.gz
2019-11-08 16:32:41,399   elapsed time: 0.006 sec
2019-11-08 16:32:41,481 Reading update date file https://icxc.cfa.harvard.edu/aspect/cheta/sync/acis2eng/2019-11-06T0234z/5min.pkl.gz
2019-11-08 16:32:41,487   elapsed time: 0.006 sec
2019-11-08 16:32:41,581 Reading update date file https://icxc.cfa.harvard.edu/aspect/cheta/sync/acis2eng/2019-11-07T0344z/5min.pkl.gz
2019-11-08 16:32:41,587   elapsed time: 0.006 sec
2019-11-08 16:32:41,590 Applying updates to 101 h5 files
Traceback (most recent call last):
  File "/Users/javierg/SAO/miniconda3/envs/ska3-cheta/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/javierg/SAO/miniconda3/envs/ska3-cheta/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/javierg/SAO/miniconda3/envs/ska3-cheta/lib/python3.6/site-packages/Ska.engarchive-4.47-py3.6.egg/cheta/update_client_archive.py", line 845, in <module>
    main()
  File "/Users/javierg/SAO/miniconda3/envs/ska3-cheta/lib/python3.6/site-packages/Ska.engarchive-4.47-py3.6.egg/cheta/update_client_archive.py", line 834, in main
    sync_stat_archive(opt, fetch.msid_files, logger, content, stat, index_tbl)
  File "/Users/javierg/SAO/miniconda3/envs/ska3-cheta/lib/python3.6/site-packages/Ska.engarchive-4.47-py3.6.egg/cheta/update_client_archive.py", line 532, in sync_stat_archive
    append_stat_col(dat, stat_file, msid, date_id, opt, logger)
  File "/Users/javierg/SAO/miniconda3/envs/ska3-cheta/lib/python3.6/site-packages/Ska.engarchive-4.47-py3.6.egg/cheta/update_client_archive.py", line 652, in append_stat_col
    raise ValueError(f'ERROR: unexpected discontinuity for stat msid={msid} '
ValueError: ERROR: unexpected discontinuity for stat msid=1MCATATR content=acis2eng
Looks like your archive is in a bad state, CONTACT your local Ska expert with this info:
  First row0 in new data 1910179 != length of existing data 1896260
```

**Comment by jeanconn** [comment]
From the discussion we were having at the cheta meeting and those errors, it looks to me like the data in your environment is too old to cheta-sync successfully.

**Comment by javierggt** [comment]
the funny thing is I did the sync the other day

**Comment by jeanconn** [comment]
Ah.  Good information!  So indeed suggests something else wrong.

**Comment by javierggt** [comment]
unless I did something slightly differently...

**Comment by jskrist** [comment]
This can happen if you updated or synced with the original PR, and then tried to sync again after it was modified and merged. @taldcroft mentioned this to me when I encountered the same issue this week.

**Comment by taldcroft** [comment]
You need to remove the file $SKA/data/eng_archive/data/acis2eng/5min/last_date_id, and possibly other instances of that file.  I need to do something better, this `last_date_id` is a weak point and at least during development has a habit of causing problems.  It is always safe to delete, it is just there to make the sync updates faster.

Also a good idea to update to 4.47.2.

**Comment by taldcroft** [comment]
(and by 4.47.2 I mean master since I didn't tag 4.47.2 yet).

**Comment by taldcroft** [comment]
I think I can catch this exception and then apply the fix I just mentioned automatically.  BTW did you do a `--dry-run` update at any point?  That was (before 4.47.1, https://github.com/sot/eng_archive/pull/177/files#diff-f8387ca20caf62130a8822e9a96bb748R556) a known way to get the `last_date_id` out of sync.
